### PR TITLE
Add script to import new card data

### PR DESCRIPTION
**Pull request by plural**
Just a shell script for the docker command to pull in new card data.

### CODE REVIEW

**Comment by Absotively** [comment]
Please list out the exact commands for updating cards in a code block in the readme, to match how other instructions are presented.

Aside from that, this looks good to me.

**Comment by plural** [comment]
good call.   Thanks for taking a look.

**Comment by Absotively** [comment]
Please add the submodule update command to the example code block too.

**Comment by plural** [comment]
Done.

**Pull request merged**
